#!/bin/sh

set -e

js="song-designer.js"
min="song-designer.min.js"
css="syn-bulma.css"
cssmin="syn-bulma.min.css"

elm make --optimize --output=$js src/Main.elm

uglifyjs $js --compress "pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe" | uglifyjs --mangle --output $min

echo "Initial JavaScript size: $(cat $js | wc -c) bytes  ($js)"
echo "Minified JavaScript size:$(cat $min | wc -c) bytes  ($min)"
echo "Gzipped size: $(cat $min | gzip -c | wc -c) bytes"


mv $js assets/$js;
mv $min assets/$min;

cd ../syn-bulma;
npm run css-build;

cp css/syn-bulma.css ../song-designer/$css;
cd ../song-designer;

uglifycss $css > $cssmin;

echo "Initial Stylesheet size: $(cat $css | wc -c) bytes  ($css)";
echo "Minified Stylesheet size:$(cat $cssmin | wc -c) bytes  ($cssmin)";

mv $css assets/$css;
mv $cssmin assets/$cssmin;



